// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC41UyM_iQx-HOBbQo2NYJKQebfUVqp_Gg',
    appId: '1:486777217674:web:bfa90a5c5f33333df54373',
    messagingSenderId: '486777217674',
    projectId: 'estudaai-abb31',
    authDomain: 'estudaai-abb31.firebaseapp.com',
    storageBucket: 'estudaai-abb31.firebasestorage.app',
    measurementId: 'G-DQF8QJTSCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM2jScX3INg5RCpGhFCQNACVjXxfizoUg',
    appId: '1:486777217674:android:da597bd6b014c9dbf54373',
    messagingSenderId: '486777217674',
    projectId: 'estudaai-abb31',
    storageBucket: 'estudaai-abb31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtuzfBHk8D_IWCSVh4Fu_jjcqlAZJh2ng',
    appId: '1:486777217674:ios:6d6f687ded22ffecf54373',
    messagingSenderId: '486777217674',
    projectId: 'estudaai-abb31',
    storageBucket: 'estudaai-abb31.firebasestorage.app',
    iosBundleId: 'com.example.estudaai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtuzfBHk8D_IWCSVh4Fu_jjcqlAZJh2ng',
    appId: '1:486777217674:ios:6d6f687ded22ffecf54373',
    messagingSenderId: '486777217674',
    projectId: 'estudaai-abb31',
    storageBucket: 'estudaai-abb31.firebasestorage.app',
    iosBundleId: 'com.example.estudaai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC41UyM_iQx-HOBbQo2NYJKQebfUVqp_Gg',
    appId: '1:486777217674:web:a70dd363d7e0708ff54373',
    messagingSenderId: '486777217674',
    projectId: 'estudaai-abb31',
    authDomain: 'estudaai-abb31.firebaseapp.com',
    storageBucket: 'estudaai-abb31.firebasestorage.app',
    measurementId: 'G-NM90BQN0W0',
  );
}
